package lv.javaguru.student_ivan_k.homework.lesson_5.level_2intern.task_13;

import java.util.Random;

class ArrayThreSum {

    public static void main(String[] args) {

        int[] numbers = new int[3];
        Random rand = new Random();
        System.out.println("Numbers are  generated by RANDOMIZER");
        int sum = 0;
        for (int i = 0; i < numbers.length; i++){
            numbers[i] = rand.nextInt(11);
            sum += numbers[i];
            System.out.println(numbers[i]);
        }
        System.out.println("Sum = " + sum);
    }
}
