package main.java.lv.javaguru.student_ivan_k.homework.lesson_5.level_2intern.task_13;

import java.util.Random;

class ArrayThreSum {

    public static void main(String[] args) {

        int[] numbers = new int[3];
        Random rand = new Random();
        System.out.println("Numbers are  generated by RANDOMIZER");
        numbers[0] = rand.nextInt(11);
        numbers[1] = rand.nextInt(11);
        numbers[2] = rand.nextInt(11);
        int sum = 0;
        for (int i = 0; i < numbers.length; i++){
            sum += numbers[i];
        }
        System.out.println(numbers[0]);
        System.out.println(numbers[1]);
        System.out.println(numbers[2]);
        System.out.println("Sum = " + sum);
    }
}
