package lv.javaguru.student_ivan_k.homework.lesson_5.level_2intern.task_12;

import java.util.Random;

class ArrayThreRandom {


    public static void main(String[] args) {

        int[] numbers = new int[3];
        Random rand = new Random();
        System.out.println("Numbers are  generated by RANDOMIZER");
        numbers[0] = rand.nextInt(11);
        numbers[1] = rand.nextInt(11);
        numbers[2] = rand.nextInt(11);
        System.out.println("Array is DONE! ");
        System.out.println(numbers[0]);
        System.out.println(numbers[1]);
        System.out.println(numbers[2]);


    }
}